{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[0m\n",
      "\u001b[34m\u001b[1m  You can now view your Streamlit app in your browser.\u001b[0m\n",
      "\u001b[0m\n",
      "\u001b[34m  Local URL: \u001b[0m\u001b[1mhttp://localhost:8501\u001b[0m\n",
      "\u001b[34m  Network URL: \u001b[0m\u001b[1mhttp://157.136.73.104:8501\u001b[0m\n",
      "\u001b[0m\n",
      "2024-09-04 13:49:36.649 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 148, in <module>\n",
      "    pie_chart = alt.Chart(data).mark_arc().encode(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 234, in __getattr__\n",
      "    return _getattr(attr)\n",
      "AttributeError: 'Chart' object has no attribute 'mark_arc'\n",
      "2024-09-04 13:50:45.347 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 149, in <module>\n",
      "    theta=alt.Theta(field='value', type='quantitative', stack=True),\n",
      "AttributeError: module 'altair' has no attribute 'Theta'\n",
      "/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py:96: UserWarning: data of type <class 'pandas.core.series.Series'> not recognized\n",
      "  warnings.warn(\"data of type {} not recognized\".format(type(data)))\n",
      "2024-09-04 13:51:46.408 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 154, in <module>\n",
      "    st.altair_chart(chart, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 365, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 297, in to_dict\n",
      "    result = _todict({k: v for k, v in self._kwds.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 60, in _todict\n",
      "    return {k: _todict(v, validate, context) for k, v in obj.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 60, in <dictcomp>\n",
      "    return {k: _todict(v, validate, context) for k, v in obj.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 56, in _todict\n",
      "    return obj.to_dict(validate=validate, context=context)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 297, in to_dict\n",
      "    result = _todict({k: v for k, v in self._kwds.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 60, in _todict\n",
      "    return {k: _todict(v, validate, context) for k, v in obj.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 60, in <dictcomp>\n",
      "    return {k: _todict(v, validate, context) for k, v in obj.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 56, in _todict\n",
      "    return obj.to_dict(validate=validate, context=context)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/schema/channels.py\", line 46, in to_dict\n",
      "    raise ValueError(\"{} encoding field is specified without a type; \"\n",
      "ValueError: variables encoding field is specified without a type; the type cannot be automatically inferred because the data is not specified as a pandas.DataFrame.\n",
      "/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py:96: UserWarning: data of type <class 'pandas.core.series.Series'> not recognized\n",
      "  warnings.warn(\"data of type {} not recognized\".format(type(data)))\n",
      "2024-09-04 13:51:53.523 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 154, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 365, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 297, in to_dict\n",
      "    result = _todict({k: v for k, v in self._kwds.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 60, in _todict\n",
      "    return {k: _todict(v, validate, context) for k, v in obj.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 60, in <dictcomp>\n",
      "    return {k: _todict(v, validate, context) for k, v in obj.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 56, in _todict\n",
      "    return obj.to_dict(validate=validate, context=context)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 297, in to_dict\n",
      "    result = _todict({k: v for k, v in self._kwds.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 60, in _todict\n",
      "    return {k: _todict(v, validate, context) for k, v in obj.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 60, in <dictcomp>\n",
      "    return {k: _todict(v, validate, context) for k, v in obj.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 56, in _todict\n",
      "    return obj.to_dict(validate=validate, context=context)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/schema/channels.py\", line 46, in to_dict\n",
      "    raise ValueError(\"{} encoding field is specified without a type; \"\n",
      "ValueError: variables encoding field is specified without a type; the type cannot be automatically inferred because the data is not specified as a pandas.DataFrame.\n",
      "/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py:96: UserWarning: data of type <class 'pandas.core.series.Series'> not recognized\n",
      "  warnings.warn(\"data of type {} not recognized\".format(type(data)))\n",
      "2024-09-04 13:52:08.862 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 154, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 365, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 297, in to_dict\n",
      "    result = _todict({k: v for k, v in self._kwds.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 60, in _todict\n",
      "    return {k: _todict(v, validate, context) for k, v in obj.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 60, in <dictcomp>\n",
      "    return {k: _todict(v, validate, context) for k, v in obj.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 56, in _todict\n",
      "    return obj.to_dict(validate=validate, context=context)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 297, in to_dict\n",
      "    result = _todict({k: v for k, v in self._kwds.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 60, in _todict\n",
      "    return {k: _todict(v, validate, context) for k, v in obj.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 60, in <dictcomp>\n",
      "    return {k: _todict(v, validate, context) for k, v in obj.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 56, in _todict\n",
      "    return obj.to_dict(validate=validate, context=context)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/schema/channels.py\", line 46, in to_dict\n",
      "    raise ValueError(\"{} encoding field is specified without a type; \"\n",
      "ValueError: variables encoding field is specified without a type; the type cannot be automatically inferred because the data is not specified as a pandas.DataFrame.\n",
      "/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py:96: UserWarning: data of type <class 'pandas.core.series.Series'> not recognized\n",
      "  warnings.warn(\"data of type {} not recognized\".format(type(data)))\n",
      "2024-09-04 13:52:10.067 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 153, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 365, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 297, in to_dict\n",
      "    result = _todict({k: v for k, v in self._kwds.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 60, in _todict\n",
      "    return {k: _todict(v, validate, context) for k, v in obj.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 60, in <dictcomp>\n",
      "    return {k: _todict(v, validate, context) for k, v in obj.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 56, in _todict\n",
      "    return obj.to_dict(validate=validate, context=context)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 297, in to_dict\n",
      "    result = _todict({k: v for k, v in self._kwds.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 60, in _todict\n",
      "    return {k: _todict(v, validate, context) for k, v in obj.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 60, in <dictcomp>\n",
      "    return {k: _todict(v, validate, context) for k, v in obj.items()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 56, in _todict\n",
      "    return obj.to_dict(validate=validate, context=context)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/schema/channels.py\", line 46, in to_dict\n",
      "    raise ValueError(\"{} encoding field is specified without a type; \"\n",
      "ValueError: variables encoding field is specified without a type; the type cannot be automatically inferred because the data is not specified as a pandas.DataFrame.\n",
      "/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py:96: UserWarning: data of type <class 'pandas.core.series.Series'> not recognized\n",
      "  warnings.warn(\"data of type {} not recognized\".format(type(data)))\n",
      "2024-09-04 13:52:12.439 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 152, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 374, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 307, in to_dict\n",
      "    raise SchemaValidationError(self, err)\n",
      "altair.utils.schemapi.SchemaValidationError: <unprintable SchemaValidationError object>\n",
      "2024-09-04 13:52:12.442 \n",
      "\n",
      "Streamlit was unable to parse the data from an exception in the user's script.\n",
      "This is usually due to a bug in the Exception object itself. Here is some info\n",
      "about that Exception object, so you can report a bug to the original author:\n",
      "\n",
      "Exception type:\n",
      "  SchemaValidationError\n",
      "\n",
      "Problem:\n",
      "  sequence item 1: expected str instance, int found\n",
      "\n",
      "Traceback:\n",
      "File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/exception.py\", line 120, in marshall\n",
      "    exception_proto.message = str(exception).strip()\n",
      "File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 103, in __str__\n",
      "    schema_path = '->'.join(val for val in schema_path[:-1]\n",
      "\n",
      "        \n",
      "/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py:96: UserWarning: data of type <class 'pandas.core.series.Series'> not recognized\n",
      "  warnings.warn(\"data of type {} not recognized\".format(type(data)))\n",
      "2024-09-04 13:52:13.581 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 151, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 374, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 307, in to_dict\n",
      "    raise SchemaValidationError(self, err)\n",
      "altair.utils.schemapi.SchemaValidationError: <unprintable SchemaValidationError object>\n",
      "2024-09-04 13:52:13.583 \n",
      "\n",
      "Streamlit was unable to parse the data from an exception in the user's script.\n",
      "This is usually due to a bug in the Exception object itself. Here is some info\n",
      "about that Exception object, so you can report a bug to the original author:\n",
      "\n",
      "Exception type:\n",
      "  SchemaValidationError\n",
      "\n",
      "Problem:\n",
      "  sequence item 1: expected str instance, int found\n",
      "\n",
      "Traceback:\n",
      "File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/exception.py\", line 120, in marshall\n",
      "    exception_proto.message = str(exception).strip()\n",
      "File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 103, in __str__\n",
      "    schema_path = '->'.join(val for val in schema_path[:-1]\n",
      "\n",
      "        \n",
      "/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py:96: UserWarning: data of type <class 'pandas.core.series.Series'> not recognized\n",
      "  warnings.warn(\"data of type {} not recognized\".format(type(data)))\n",
      "2024-09-04 13:52:19.282 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 147, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 374, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 307, in to_dict\n",
      "    raise SchemaValidationError(self, err)\n",
      "altair.utils.schemapi.SchemaValidationError: Invalid specification\n",
      "\n",
      "        altair.vegalite.v4.api.Chart, validating 'required'\n",
      "\n",
      "        'mark' is a required property\n",
      "        \n",
      "/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py:96: UserWarning: data of type <class 'pandas.core.series.Series'> not recognized\n",
      "  warnings.warn(\"data of type {} not recognized\".format(type(data)))\n",
      "2024-09-04 13:52:27.227 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 147, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 374, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 307, in to_dict\n",
      "    raise SchemaValidationError(self, err)\n",
      "altair.utils.schemapi.SchemaValidationError: Invalid specification\n",
      "\n",
      "        altair.vegalite.v4.api.Chart, validating 'required'\n",
      "\n",
      "        'mark' is a required property\n",
      "        \n",
      "/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py:96: UserWarning: data of type <class 'pandas.core.series.Series'> not recognized\n",
      "  warnings.warn(\"data of type {} not recognized\".format(type(data)))\n",
      "2024-09-04 13:52:45.242 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 147, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 374, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 307, in to_dict\n",
      "    raise SchemaValidationError(self, err)\n",
      "altair.utils.schemapi.SchemaValidationError: Invalid specification\n",
      "\n",
      "        altair.vegalite.v4.api.Chart, validating 'required'\n",
      "\n",
      "        'mark' is a required property\n",
      "        \n",
      "/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py:96: UserWarning: data of type <class 'pandas.core.series.Series'> not recognized\n",
      "  warnings.warn(\"data of type {} not recognized\".format(type(data)))\n",
      "2024-09-04 13:52:48.187 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 147, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 374, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 307, in to_dict\n",
      "    raise SchemaValidationError(self, err)\n",
      "altair.utils.schemapi.SchemaValidationError: Invalid specification\n",
      "\n",
      "        altair.vegalite.v4.api.Chart, validating 'required'\n",
      "\n",
      "        'mark' is a required property\n",
      "        \n",
      "/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py:96: UserWarning: data of type <class 'pandas.core.series.Series'> not recognized\n",
      "  warnings.warn(\"data of type {} not recognized\".format(type(data)))\n",
      "2024-09-04 13:53:19.155 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 147, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 374, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 307, in to_dict\n",
      "    raise SchemaValidationError(self, err)\n",
      "altair.utils.schemapi.SchemaValidationError: Invalid specification\n",
      "\n",
      "        altair.vegalite.v4.api.Chart, validating 'required'\n",
      "\n",
      "        'mark' is a required property\n",
      "        \n",
      "/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py:96: UserWarning: data of type <class 'pandas.core.series.Series'> not recognized\n",
      "  warnings.warn(\"data of type {} not recognized\".format(type(data)))\n",
      "2024-09-04 13:53:47.148 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 148, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 374, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 307, in to_dict\n",
      "    raise SchemaValidationError(self, err)\n",
      "altair.utils.schemapi.SchemaValidationError: Invalid specification\n",
      "\n",
      "        altair.vegalite.v4.api.Chart, validating 'required'\n",
      "\n",
      "        'mark' is a required property\n",
      "        \n",
      "/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py:96: UserWarning: data of type <class 'pandas.core.series.Series'> not recognized\n",
      "  warnings.warn(\"data of type {} not recognized\".format(type(data)))\n",
      "2024-09-04 13:53:50.115 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 148, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 374, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 307, in to_dict\n",
      "    raise SchemaValidationError(self, err)\n",
      "altair.utils.schemapi.SchemaValidationError: Invalid specification\n",
      "\n",
      "        altair.vegalite.v4.api.Chart, validating 'required'\n",
      "\n",
      "        'mark' is a required property\n",
      "        \n",
      "/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py:96: UserWarning: data of type <class 'pandas.core.series.Series'> not recognized\n",
      "  warnings.warn(\"data of type {} not recognized\".format(type(data)))\n",
      "2024-09-04 13:53:54.646 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 148, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 374, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 307, in to_dict\n",
      "    raise SchemaValidationError(self, err)\n",
      "altair.utils.schemapi.SchemaValidationError: Invalid specification\n",
      "\n",
      "        altair.vegalite.v4.api.Chart, validating 'required'\n",
      "\n",
      "        'mark' is a required property\n",
      "        \n",
      "2024-09-04 13:54:05.455 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 135, in <module>\n",
      "    metrics_pie = metrics[metrics['city'] == st.session_state.selected_city.lower()][['temporal (%)', 'spatial (%)']].iloc[0].re\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/pandas/core/generic.py\", line 5575, in __getattr__\n",
      "    return object.__getattribute__(self, name)\n",
      "AttributeError: 'Series' object has no attribute 're'\n",
      "/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/type_util.py:956: UserWarning: The DataFrame has column names of mixed type. They will be converted to strings and not roundtrip correctly.\n",
      "  table = pa.Table.from_pandas(df)\n",
      "2024-09-04 13:54:06.589 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 148, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 374, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 307, in to_dict\n",
      "    raise SchemaValidationError(self, err)\n",
      "altair.utils.schemapi.SchemaValidationError: Invalid specification\n",
      "\n",
      "        altair.vegalite.v4.api.Chart, validating 'required'\n",
      "\n",
      "        'mark' is a required property\n",
      "        \n",
      "/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/type_util.py:956: UserWarning: The DataFrame has column names of mixed type. They will be converted to strings and not roundtrip correctly.\n",
      "  table = pa.Table.from_pandas(df)\n",
      "2024-09-04 13:54:16.541 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 149, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 374, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 307, in to_dict\n",
      "    raise SchemaValidationError(self, err)\n",
      "altair.utils.schemapi.SchemaValidationError: Invalid specification\n",
      "\n",
      "        altair.vegalite.v4.api.Chart, validating 'required'\n",
      "\n",
      "        'mark' is a required property\n",
      "        \n",
      "2024-09-04 13:54:17.810 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 149, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 374, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 307, in to_dict\n",
      "    raise SchemaValidationError(self, err)\n",
      "altair.utils.schemapi.SchemaValidationError: Invalid specification\n",
      "\n",
      "        altair.vegalite.v4.api.Chart, validating 'required'\n",
      "\n",
      "        'mark' is a required property\n",
      "        \n",
      "2024-09-04 13:54:28.312 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 149, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 374, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 307, in to_dict\n",
      "    raise SchemaValidationError(self, err)\n",
      "altair.utils.schemapi.SchemaValidationError: Invalid specification\n",
      "\n",
      "        altair.vegalite.v4.api.Chart, validating 'required'\n",
      "\n",
      "        'mark' is a required property\n",
      "        \n",
      "2024-09-04 13:54:31.452 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 150, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 374, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 307, in to_dict\n",
      "    raise SchemaValidationError(self, err)\n",
      "altair.utils.schemapi.SchemaValidationError: Invalid specification\n",
      "\n",
      "        altair.vegalite.v4.api.Chart, validating 'required'\n",
      "\n",
      "        'mark' is a required property\n",
      "        \n",
      "2024-09-04 13:54:35.462 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 542, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/Volumes/Fatboy/Indian Traffic/cities/streamlit/cities/pages/2 Model Results.py\", line 150, in <module>\n",
      "    st.altair_chart(chart2, use_container_width=True)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
      "    result = non_optional_func(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 798, in altair_chart\n",
      "    marshall(\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py\", line 1533, in marshall\n",
      "    chart_dict = altair_chart.to_dict()\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/vegalite/v4/api.py\", line 374, in to_dict\n",
      "    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)\n",
      "  File \"/Users/rmitta/opt/anaconda3/envs/zerotwo/lib/python3.10/site-packages/altair/utils/schemapi.py\", line 307, in to_dict\n",
      "    raise SchemaValidationError(self, err)\n",
      "altair.utils.schemapi.SchemaValidationError: Invalid specification\n",
      "\n",
      "        altair.vegalite.v4.api.Chart, validating 'required'\n",
      "\n",
      "        'mark' is a required property\n",
      "        \n"
     ]
    }
   ],
   "source": [
    "!streamlit run Data_Overview.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "p = 'data/variability/bhopal/2021/car_F_COUNT_variability.png'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "File exists\n"
     ]
    }
   ],
   "source": [
    "# chceck if p has a file\n",
    "import os\n",
    "if os.path.isfile(p):\n",
    "       print('File exists')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10.6 ('zerotwo')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.6"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "9bfb04bc2ddf749979761a4feac0c518cf5ca390f648d1feb34c0cf89edffd23"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
